[general]
enable_bucket = true
resolution = 512
flip_aug = true

random_crop = false
color_aug = false

[[datasets]]
  [[datasets.subsets]]
#  image_dir = "CASE_SK3D/dataset/CASE_NAME/tis_right/rgb/undistorted/ambient@best"
  image_dir = "CASE_SK3D/CASE_NAME/googlesearch"
#  '/root/project/kaust/Diffuse-Neus/public_data/sk3d/CASE_NAME/image'
#  class_tokens = 'a photo of a INIT_WORD in the style of shs'
  class_tokens = 'a photo of a shs'
  num_repeats = 5 
